### ISSUE TITLE
When will you open the  source of b2d

### ISSUE THREAD

**Issue by prepare** [blend2d/blend2d-samples#1]
Hello,  @kobalicek.

CHEER!

I'm a _Maxim's Agg_ fan club. 

I see a blank repo b2d(https://github.com/blend2d/b2d),
when will you open the  source of b2d(https://github.com/blend2d/b2d) ?
 
---

:)

**Comment by kobalicek** [comment]
Hello, please drop me an email an I will provide you the alpha release. Public release is planned within a month, but you can participate in alpha to get it earlier.

**Comment by prepare** [comment]
@kobalicek ,

my email is wintercoredev [at] gmail.com

:)

**Comment by prepare** [comment]
Thank you.
I've got your email

:)
