### ISSUE TITLE
SIGABRT when running Qt samples

### ISSUE THREAD

**Issue by ghost** [blend2d/blend2d-samples#2]
Hello. I am unable to run the following Qt samples:

- bl-qt-bounces
- bl-qt-circles
- bl-qt-elliptica
- bl-qt-gradients
- bl-qt-particles
- bl-qt-stroke
- bl-qt-tiger

Qt samples not in the above list run OK.

The printed error message is:

    [Blend2D] ASSERTION FAILURE: 'tVal > 0.0' at 'blend2d/src/blend2d/raster/edgebuilder_p.h' [line 1790]

Backtrace: [bl-qt-bounces.txt](https://github.com/blend2d/blend2d-samples/files/4505444/bl-qt-bounces.txt)

**Comment by kobalicek** [comment]
I'm wondering which compilation flags were used to build the binary? I have some suspects, but I would like to see.

**Comment by atomsymbol** [comment]
I used `cmake .` in all four blend2d directories (asmjit, blend2d, blend2d-bench, blend2d-samples). Then I used `cmake -DCMAKE_BUILT_TYPE=Debug` in `blend2-samples/qt` to get a backtrace with line numbers. It seems `BL_BUILD_DEBUG` gets enabled in api.h via `ifndef NDEBUG`, but I would need to check to be sure.

gdb says that the value of tVal is `-0`.

**Comment by kobalicek** [comment]
Since this is on Gentoo I'm wondering whether there are custom user flags affecting the compilation.

**Comment by atomsymbol** [comment]
The cause of the issue is that Blend2D code is executing with DAZ (denormals are zeros) flag set in the MXCSR register. Because of this, in `blQuadRoots` the comparison `x0 >= tMin` evaluates to `true` for the following values:

    x0 = -0.0;
    tMin = 4.94066e-324; // Smallest float64 value greater than zero

Sample code for testing:

Note: Use `-fno-inline` when compiling this code to prevent constant propagation when compiling with for example `-O2`.

    #include <stdint.h>
    #include <stdio.h>
    #include <xmmintrin.h>

    union U {
        double d;
        int64_t i;
    };

    double fa() {
        union U u;
        u.d = -0.0;
        //u.i = 0x8000000000000000ULL;
        return u.d;
    }

    double fb() {
        union U u;
        u.d = 4.94066e-324;
        //u.i = 0x1ULL;
        return u.d;
    }

    int main(int argc, char **argv) {
        double a = fa();
        double b = fb();

        // Set DAZ (denormals are zero)
        if(1) _mm_setcsr(_mm_getcsr() | (1 << 6)); 

        printf("%g %g %d\n", a, b, a >= b);
        return 0;
    }

**Comment by kobalicek** [comment]
Thanks! Denormals was actually my suspect, but I wasn't sure.

I have created https://github.com/blend2d/blend2d/issues/74 as this is a Blend2D bug.

**Comment by atomsymbol** [comment]
> Sample code for testing:
> 
> Note: Use `-fno-inline` when compiling this code to prevent constant propagation when compiling with for example `-O2`.
> 
> ```
> #include <stdint.h>
> #include <stdio.h>
> 
> union U {
>     double d;
>     uint64_t i;
> };
> 
> double fa() {
>     union U u;
>     u.d = -0.0;
>     //u.i = 0x8000000000000000ULL;
>     return u.d;
> }
> 
> double fb() {
>     union U u;
>     u.d = 4.94066e-324;
>     //u.i = 0x1ULL;
>     return u.d;
> }
> 
> int main(int argc, char **argv) {
>     double a = fa();
>     double b = fb();
>     printf("%g %g %d\n", a, b, a >= b);
>     return 0;
> }
> ```

The above code, without _mm_setscr, correctly prints that `a >= b` is false on Raspberry Pi 2 (armv7l). With `-funsafe-math-optimizations` it prints true. The assembly code of `main()` is the same in these two cases.
