### ISSUE TITLE
Cannot open include file: 'bl-qt-static.h': No such file or directory

### ISSUE THREAD

**Issue by ianharrigan** [blend2d/blend2d-samples#3]
As stated in the title, i cant build (on windows) due to `bl-qt-static.h` not being located. Ive looked in the sources (locally and github) and cant seem to find it anywhere, is this a generated file or something?

Am i doing something drastically wrong?

Cheers,
Ian

**Comment by kobalicek** [comment]
No, the file is unfortunately missing. It's actually not doing anything, I will fix this.

**Comment by kobalicek** [comment]
Should be fixed by https://github.com/blend2d/blend2d-samples/commit/46deb4a1cd3d7026c5efeea5e417307f87ee8ee4

**Comment by ianharrigan** [comment]
Great, thanks!
