### ISSUE TITLE
Samples create images different than the Getting Started examples

### ISSUE THREAD

**Issue by stoeckley** [blend2d/blend2d-samples#5]
I've run all these examples, and a few of them do not match the output on the [Getting Started](https://blend2d.com/doc/getting-started.html) page.

Here are some of them:

![bl-getting-started-3](https://user-images.githubusercontent.com/4611759/217939603-0f3f66f8-eb79-41b7-b632-f51ecda319a3.png)
![bl-getting-started-4](https://user-images.githubusercontent.com/4611759/217939607-5a31c473-b140-4b8f-909a-5a7cceaa7983.png)
![bl-getting-started-5](https://user-images.githubusercontent.com/4611759/217939611-003ef104-c2d1-4d5c-9c84-0643aa046817.png)

**Comment by kobalicek** [comment]
These samples were moved to blend2d project (not anymore part of blend2d-apps project) and they should all work now, so I'm closing this issue.

Please reopen a bug on Blend2D side if they are still not working for you.
